[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fatima Anne Camero", email = "54559570+timamero@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.62",
    "moto[s3]>=5.2.2",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
